import { MCPServer } from './types';

export const mockServers: MCPServer[] = [
  {
    id: 'mcp-customer-data',
    name: 'Customer Data MCP',
    version: '2.4.1',
    status: 'APPROVED',
    category: 'Customer Data',
    description: 'Secure access to customer profiles, account summaries, and usage history',
    tools: [
      { name: 'get_account_summary', description: 'Retrieve current account summary', scope: 'read:customer.account', approved: true },
      { name: 'get_user_profile', description: 'Fetch customer profile data', scope: 'read:customer.profile', approved: true },
      { name: 'get_usage_history', description: 'Query usage history records', scope: 'read:customer.usage', approved: true },
      { name: 'update_contact_info', description: 'Modify customer contact details', scope: 'write:customer.profile', approved: true },
    ],
    connectionString: 'npx -y @modelcontextprotocol/server-customer-data',
    maintainer: 'Platform Team',
    lastUpdated: '2026-04-10',
    requestedScopes: ['read:customer.account', 'read:customer.profile', 'read:customer.usage', 'write:customer.profile'],
    allowedScopes: ['read:customer.account', 'read:customer.profile', 'read:customer.usage', 'write:customer.profile'],
  },
  {
    id: 'mcp-security-analytics',
    name: 'Security Analytics MCP',
    version: '1.8.0',
    status: 'APPROVED',
    category: 'Security & Compliance',
    description: 'Real-time anomaly detection and risk scoring engine',
    tools: [
      { name: 'calculate_risk_score', description: 'Compute risk score for an event', scope: 'execute:risk.score', approved: true },
      { name: 'check_anomaly_indicators', description: 'Analyze anomaly patterns', scope: 'read:security.anomalies', approved: true },
      { name: 'flag_suspicious_activity', description: 'Mark activity for review', scope: 'write:security.alerts', approved: true },
    ],
    connectionString: 'docker run -p 3000:3000 acme-corp/mcp-security-analytics:1.8.0',
    maintainer: 'Security Engineering',
    lastUpdated: '2026-04-15',
    requestedScopes: ['execute:risk.score', 'read:security.anomalies', 'write:security.alerts'],
    allowedScopes: ['execute:risk.score', 'read:security.anomalies', 'write:security.alerts'],
  },
  {
    id: 'mcp-document-processor',
    name: 'Document Intelligence MCP',
    version: '3.1.0',
    status: 'PENDING',
    category: 'Document Processing',
    description: 'OCR, classification, and extraction for uploaded documents',
    tools: [
      { name: 'extract_document_data', description: 'Parse uploaded document forms', scope: 'read:documents.content', approved: false },
      { name: 'classify_document_type', description: 'Auto-categorize uploaded docs', scope: 'read:documents.metadata', approved: false },
      { name: 'generate_pdf_summary', description: 'Create executive summaries', scope: 'write:documents.reports', approved: false },
      { name: 'validate_document_format', description: 'Check uploaded files meet format requirements', scope: 'read:documents.validate', approved: false },
    ],
    connectionString: 'mcp://example.local/document-processor',
    maintainer: 'Data Science Team',
    lastUpdated: '2026-04-17',
    requestedScopes: ['read:documents.content', 'read:documents.metadata', 'write:documents.reports', 'read:documents.validate'],
    allowedScopes: ['read:documents.content', 'read:documents.metadata', 'write:documents.reports'],
  },
  {
    id: 'mcp-billing-payments',
    name: 'Billing & Payments MCP',
    version: '2.0.5',
    status: 'APPROVED',
    category: 'Infrastructure',
    description: 'Payment processing, refunds, and transaction settlement for platform billing',
    tools: [
      { name: 'process_payment', description: 'Execute payment transaction', scope: 'execute:payment.process', approved: true },
      { name: 'issue_refund', description: 'Process customer refund', scope: 'execute:payment.refund', approved: true },
      { name: 'check_settlement_status', description: 'Query settlement state', scope: 'read:payment.settlement', approved: true },
    ],
    connectionString: 'https://api.example.local/mcp/billing',
    maintainer: 'Billing Team',
    lastUpdated: '2026-04-12',
    requestedScopes: ['execute:payment.process', 'execute:payment.refund', 'read:payment.settlement'],
    allowedScopes: ['execute:payment.process', 'execute:payment.refund', 'read:payment.settlement'],
  },
  {
    id: 'mcp-analytics-warehouse',
    name: 'Data Warehouse Connector',
    version: '1.5.2',
    status: 'APPROVED',
    category: 'Analytics',
    description: 'Read-only access to platform data warehouse',
    tools: [
      { name: 'query_customer_segments', description: 'Run segmentation queries', scope: 'read:warehouse.segments', approved: true },
      { name: 'fetch_kpi_metrics', description: 'Retrieve business KPIs', scope: 'read:warehouse.kpis', approved: true },
      { name: 'export_dataset', description: 'Export data for analysis', scope: 'read:warehouse.export', approved: true },
    ],
    connectionString: 'jdbc:postgresql://warehouse.example.local:5432/analytics',
    maintainer: 'Analytics Platform',
    lastUpdated: '2026-04-08',
    requestedScopes: ['read:warehouse.segments', 'read:warehouse.kpis', 'read:warehouse.export'],
    allowedScopes: ['read:warehouse.segments', 'read:warehouse.kpis', 'read:warehouse.export'],
  },
];

export const categories = [
  'All Servers',
  'Customer Data',
  'Security & Compliance',
  'Document Processing',
  'Analytics',
  'Infrastructure',
];
